### ISSUE TITLE
Suggestion: better formatting of log files

### ISSUE THREAD

**Issue by skiaphrene** [fmicompbio/QuasR#27]
Just an idea: could use some other printing method (eg cat) to get a more readable log file, without all the square brackets and quotes.
Cheers,
-- Alex

**Comment by skiaphrene** [comment]
Adding to this, perhaps have a timestamp preceding each line, to get a better idea of full/per-step runtimes.

**Comment by mbstadler** [comment]
Thanks for the suggestion! Would you be able to provide a PR?

**Comment by skiaphrene** [comment]
I made my first Pull Request!: 
#40

**Comment by mbstadler** [comment]
I will close this - it has been addressed in #40, thank you for your contribution @skiaphrene
