### ISSUE TITLE
Paired option in qAlign

### ISSUE THREAD

**Issue by damisiak** [fmicompbio/QuasR#44]
I tries to use the paired option when using bam files and get the following error if paired is "rf":

 proj <- qAlign(sampleFile = sample.file, paired = "rf",
              genome = genome.file, splicedAlignment = T,
              aligner = "Rhisat2")

Error in if (proj@aligner == "Rbowtie" && proj@splicedAlignment && !(proj@paired %in%  : 
  missing value where TRUE/FALSE needed

If I use "fr" instead it works fine or if I set splicedAlignment = F.
But I have rf paired spliced aligned data so far.

Maybe a bug in the code? How important these options are by providing .bam files already?

Best,
Danny

**Comment by damisiak** [comment]
Just a hint for this, obviously qAlign falls back to Rbowtie as aligner, although I put Rhisat2 as option, and Bowtie do not have an "rf" option as I know.

**Comment by csoneson** [comment]
Hi @damisiak, thanks for raising this issue. Indeed, it was a subtle bug that would only manifest if the inputs were .bam files and an unsupported paired option for `Rbowtie` was selected (independently of which aligner was actually specified - it didn't "fall back" to `Rbowtie`, but rather failed in a check that involved `Rbowtie` and `paired` options). We have fixed this in `devel` and release 3.18, and the updated versions will be available from Bioconductor in a day or two. You could also install the updated version directly from the respective branch on GitHub. Or, finally, if you provide .bam files as input, these parameters don't really matter/are not used, so you could temporarily work around it by specifying a supported `paired` option. 

I will close this issue, but feel free to reopen if there are still problems.
